// Auto-generated by: npx supabase gen types typescript --local > types/database.ts
// Run after `npx supabase start` and migrations are applied.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      rooms: {
        Row: {
          id: string;
          topic: string;
          created_at: string;
          summary: string | null;
        };
        Insert: {
          id?: string;
          topic: string;
          created_at?: string;
          summary?: string | null;
        };
        Update: {
          id?: string;
          topic?: string;
          created_at?: string;
          summary?: string | null;
        };
      };
      messages: {
        Row: {
          id: string;
          room_id: string;
          author: string;
          content: string;
          created_at: string;
          is_ai: boolean;
        };
        Insert: {
          id?: string;
          room_id: string;
          author: string;
          content: string;
          created_at?: string;
          is_ai?: boolean;
        };
        Update: {
          id?: string;
          room_id?: string;
          author?: string;
          content?: string;
          created_at?: string;
          is_ai?: boolean;
        };
      };
      participants: {
        Row: {
          id: string;
          room_id: string;
          name: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          room_id: string;
          name: string;
          joined_at?: string;
        };
        Update: {
          id?: string;
          room_id?: string;
          name?: string;
          joined_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
